pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/Fayaz-2/cloud-based-ci-cd-flask-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('myflaskapp', './app')
                }
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh 'ansible-playbook ansible/deploy.yml'
            }
        }
    }
}

