---
- name: Deploy Flask App Container
  hosts: localhost
  tasks:
    - name: Stop old container
      shell: docker stop flask_app || true && docker rm flask_app || true

    - name: Run new container
      shell: docker run -d -p 5000:5000 --name flask_app myflaskapp:latest

